"use client";
import { FormEvent, useState } from "react";
import styles from "./page.module.css";
type FormState = { certificate: string; timing: string; name: string; contact: string; preferred: string };
const initialForm: FormState = { certificate: "", timing: "", name: "", contact: "", preferred: "whatsapp" };
export default function Home() {
  const [form, setForm] = useState(initialForm); const [status, setStatus] = useState<"idle" | "loading" | "success">("idle"); const [error, setError] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!form.certificate || !form.timing || !form.name || !form.contact) { setError("Completá los campos marcados para poder orientarte."); return; } setError(""); setStatus("loading"); window.setTimeout(() => setStatus("success"), 700); }
  function update(field: keyof FormState, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  return <div className={styles.page}><header className={styles.nav}><a href="#inicio" className={styles.wordmark} aria-label="MED's inicio"><span>MED&apos;s</span><small>certificados</small></a><a className={styles.navLink} href="#como-funciona">Cómo funciona <span>↘</span></a></header><main>
    <section id="inicio" className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}><span className={styles.dot} /> Medicina deportiva · Rosario</p><h1>Tu certificado,<br /><em>sin vueltas.</em></h1><p className={styles.lead}>Orientación simple para solicitar tu certificado médico deportivo o escolar, con la información justa para dar el primer paso.</p><a className={styles.primaryButton} href="#solicitar">Quiero solicitarlo <span>↘</span></a><p className={styles.note}>La evaluación y emisión dependen del profesional médico.</p></div><div className={styles.heroVisual} aria-label="Información de atención de MED's"><div className={styles.orbit} /><div className={styles.paper}><span className={styles.paperMark}>M</span><span className={styles.paperLine} /><span className={`${styles.paperLine} ${styles.short}`} /><span className={styles.paperStamp}>APTO<br />FÍSICO</span></div><div className={styles.visualTag}><strong>01</strong><span>Contanos qué<br />necesitás gestionar</span></div><div className={styles.location}>Av. Eva Perón 5861<br /><span>Rosario, Santa Fe</span></div></div></section>
    <section id="como-funciona" className={styles.steps}><p className={styles.sectionLabel}>El proceso</p><div className={styles.stepGrid}><div><span>01</span><h2>Nos contás</h2><p>Tipo de certificado y cuándo lo necesitás. Nada más.</p></div><div><span>02</span><h2>Te orientamos</h2><p>Recibís los próximos pasos y la disponibilidad de atención.</p></div><div><span>03</span><h2>Te evaluamos</h2><p>El profesional define la aptitud según corresponda.</p></div></div></section>
    <section id="solicitar" className={styles.requestSection}><div className={styles.formIntro}><p className={styles.sectionLabel}>Primer paso</p><h2>Dejanos tu consulta.<br /><em>Te guiamos.</em></h2><p>Usamos estos datos solo para contactarte y orientarte sobre el trámite.</p></div><form className={styles.form} onSubmit={submit} noValidate><label>¿Qué certificado necesitás? <select required value={form.certificate} onChange={(e) => update("certificate", e.target.value)}><option value="">Seleccioná una opción</option><option>Deportivo</option><option>Escolar</option><option>No estoy seguro/a</option></select></label><label>¿Cuándo lo necesitás? <select required value={form.timing} onChange={(e) => update("timing", e.target.value)}><option value="">Elegí una referencia</option><option>Esta semana</option><option>En los próximos 15 días</option><option>Más adelante</option></select></label><div className={styles.twoCol}><label>Tu nombre<input required value={form.name} onChange={(e) => update("name", e.target.value)} placeholder="Nombre y apellido" /></label><label>Cómo contactarte<input required value={form.contact} onChange={(e) => update("contact", e.target.value)} placeholder="Email o teléfono" /></label></div><fieldset><legend>Preferencia de contacto</legend><div className={styles.options}>{["whatsapp", "email"].map((option) => <label key={option} className={form.preferred === option ? styles.selected : ""}><input type="radio" name="preferred" value={option} checked={form.preferred === option} onChange={(e) => update("preferred", e.target.value)} /> {option === "whatsapp" ? "WhatsApp" : "Email"}</label>)}</div></fieldset>{error && <p className={styles.error} role="alert">{error}</p>}{status === "success" ? <div className={styles.success} role="status"><strong>Recibimos tu consulta.</strong><span>Te vamos a contactar para orientarte con los próximos pasos.</span></div> : <button className={styles.submit} disabled={status === "loading"}>{status === "loading" ? "Enviando…" : "Solicitar orientación ↗"}</button>}<p className={styles.formFoot}>No hace falta compartir diagnósticos ni información médica en este formulario.</p></form></section></main><footer><span>MED&apos;s · Certificados médicos deportivos y escolares</span><span>Atención de lunes a viernes</span></footer></div>;
}
