"use client";
import Image from "next/image";
import { FormEvent, useState } from "react";
import styles from "./page.module.css";

const hours = [["Lun", "Cerrado"], ["Mar · Vie", "Solo cena"], ["Sáb · Dom", "Mediodía + cena"]];

export default function Home() {
  const [sent, setSent] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = event.currentTarget; if (!form.checkValidity()) { setError("Completá los campos marcados para enviar la solicitud."); form.reportValidity(); return; } setLoading(true); window.setTimeout(() => { setLoading(false); setSent(true); }, 700); }
  return <div className={styles.page}>
    <header className={styles.nav}><a className={styles.wordmark} href="#inicio" aria-label="Restaurante Margarita, inicio"><span className={styles.mark}>M</span><span>Restaurante<br />Margarita</span></a><nav aria-label="Navegación principal"><a href="#la-casa">La casa</a><a href="#horarios">Horarios</a><a href="#solicitar">Solicitar mesa</a></nav></header>
    <main>
      <section className={styles.hero} id="inicio"><div className={styles.heroCopy}><p className={styles.kicker}>Reconquista 401 · Rosario</p><h1>Una mesa para<br /><em>quedarse.</em></h1><p className={styles.heroText}>Un restaurante en Rosario para encontrarse alrededor de la mesa.</p><a className={styles.primaryButton} href="#solicitar">Solicitar una mesa <span>↘</span></a></div><div className={styles.heroImage}><Image src="/images/hero-plated-dish.jpg" alt="Plato servido en Restaurante Margarita" fill priority sizes="(max-width: 767px) 100vw, 54vw" /><span className={styles.imageNote}>Margarita / Rosario</span></div><div className={styles.heroRail}>Cocina · encuentros · Rosario</div></section>
      <section className={styles.intro} id="la-casa"><p className={styles.sectionNo}>01 / LA CASA</p><div><h2>El tiempo también<br /><span>se sirve.</span></h2><p>Descubrí Margarita, mirá cuándo visitarnos y dejá una solicitud de mesa. El equipo confirma cada reserva.</p></div><div className={styles.introImage}><Image src="/images/ambiance-dining-room.jpg" alt="Interior del restaurante" fill sizes="(max-width: 767px) 100vw, 35vw" /></div></section>
      <section className={styles.schedule} id="horarios"><div className={styles.scheduleLead}><p className={styles.sectionNo}>02 / VISITARNOS</p><h2>Elegí tu<br /><em>momento.</em></h2></div><div className={styles.hoursList}>{hours.map(([day, value]) => <div className={styles.hourRow} key={day}><strong>{day}</strong><span>{value}</span></div>)}</div><p className={styles.scheduleNote}>Recomendamos reservar para brunch, almuerzo y cena.</p></section>
      <section className={styles.booking} id="solicitar"><div className={styles.bookingVisual}><Image src="/images/detail-table-setting.jpg" alt="Mesa preparada" fill sizes="(max-width: 767px) 100vw, 42vw" /><p>03 / TU MESA</p></div><div className={styles.bookingForm}><p className={styles.sectionNo}>SOLICITUD DE RESERVA</p><h2>Hagamos lugar.</h2>{sent ? <div className={styles.success} role="status"><span>✓</span><h3>Solicitud recibida</h3><p>Gracias. El equipo de Margarita revisará los datos y confirmará la mesa.</p><button type="button" onClick={() => setSent(false)}>Enviar otra solicitud</button></div> : <form onSubmit={submit} noValidate><label>Nombre<input name="name" required autoComplete="name" /></label><div className={styles.formGrid}><label>Fecha<input name="date" type="date" required /></label><label>Personas<select name="guests" defaultValue="2" required><option value="1">1 persona</option><option value="2">2 personas</option><option value="3">3 personas</option><option value="4">4 personas</option><option value="5">5 personas</option><option value="6">6 personas</option></select></label></div><label>Momento<select name="moment" defaultValue="cena" required><option value="brunch">Brunch</option><option value="almuerzo">Almuerzo</option><option value="cena">Cena</option></select></label>{error && <p className={styles.error} role="alert">{error}</p>}<button className={styles.submit} type="submit" disabled={loading}>{loading ? "Enviando solicitud…" : "Solicitar mesa ↗"}</button><small>La solicitud no es una confirmación automática. El equipo la revisará y responderá.</small></form>}</div></section>
    </main><footer className={styles.footer}><span>Restaurante Margarita</span><span>Reconquista 401, Rosario, Santa Fe</span><span>4.3 ★ · 1718 reseñas</span></footer>
  </div>;
}
